USE [ReportBuilder]
GO
/*Impressions*/
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,1) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,2) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,3) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,4) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,5) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,6) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,7) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,8) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,9) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,10) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,11) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,12) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,13) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,14) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,15) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,16) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (1,17) 
/*Clicks*/
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,1) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,2) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,3) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,4) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,5) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,6) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,7) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,8) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,9) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,10) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,11) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,12) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,13) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,14) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,15) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,16) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (2,17) 
/*WinningCost*/
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,1) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,2) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,3) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,4) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,5) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,6) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,7) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,8) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,9) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,10) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,11) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,12) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,13) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,14) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,15) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,16) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (3,17) 
/*BidCount*/
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (4,1) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (4,2) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (4,3) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (4,7) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (4,11) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (4,12) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (4,13) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (4,14) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (4,16) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (4,17) 
/*DealBidCount*/
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (5,1) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (5,2) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (5,3) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (5,7) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (5,8) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (5,11) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (5,12) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (5,13) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (5,14) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (5,16) 
/*PackageBidCount*/
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (6,1) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (6,2) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (6,3) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (6,7) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (6,9) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (6,11) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (6,12) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (6,13) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (6,14) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (6,16) 
/*CreativeSettingsBidCount*/
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (7,1) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (7,2) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (7,3) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (7,7) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (7,10) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (7,11) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (7,12) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (7,13) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (7,14) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (7,16) 
/*BuyRate*/
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (8,1) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (8,2) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (8,3) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (8,7) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (8,8) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (8,9) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (8,10) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (8,11) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (8,12) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (8,13) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (8,14) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (8,16) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (8,17) 
/*eCPM*/
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,1) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,2) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,3) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,4) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,5) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,6) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,7) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,8) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,9) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,10) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,11) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,12) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,13) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,14) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,15) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,16) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (9,17) 
/*eCPC*/
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,1) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,2) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,3) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,4) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,5) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,6) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,7) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,8) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,9) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,10) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,11) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,12) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,13) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,14) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,15) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,16) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (10,17) 
/*CTR*/
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,1) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,2) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,3) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,4) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,5) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,6) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,7) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,8) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,9) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,10) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,11) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,12) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,13) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,14) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,15) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,16) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (11,17) 
/*IncludedFee*/
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,1) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,2) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,3) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,4) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,5) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,6) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,7) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,8) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,9) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,10) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,11) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,12) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,13) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,14) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,15) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,16) 
INSERT INTO [dbo].[MetricDimensionMappings]([MetricId],[DimensionId])
VALUES (12,17) 