USE [TestDB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/* RERPORT COMPONENT */

CREATE TABLE [dbo].[ReportComponents](
	[ReportId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](30) NOT NULL,
	[Type] [int] NOT NULL
) ON [PRIMARY]

GO

/* METRIC */
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Metrics](
	[ID] [int] NOT NULL,
	[Mnemonic] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Metrics] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/* METRIC GROUPS */
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MetricGroups](
	[ID] [int] NOT NULL,
	[GroupName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_MetricGroups] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/* METRIC GROUPS <MAP> METRIC */
CREATE TABLE [dbo].[MetricGroupMap](
	[ID] [int] NOT NULL,
	[GroupID] [int] NOT NULL,
	[MetricID] [int] NOT NULL,
 CONSTRAINT [PK_MetricGroupMap] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UniqueCombos] UNIQUE NONCLUSTERED 
(
	[GroupID] ASC,
	[MetricID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[MetricID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/* METRIC NAME */
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MetricName](
	[ID] [int] NOT NULL,
	[NameID] [int] NOT NULL,
	[DisplayName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_MetricName] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/* METRIC DISCRIPTION */
CREATE TABLE [dbo].[MetricDescriptions](
	[ID] [int] NOT NULL,
	[MetricID] [int] NOT NULL,
	[Description] [nvarchar](300) NULL,
 CONSTRAINT [PK_MetricDescriptions] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE METRIC] UNIQUE NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[MetricID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MetricDescriptions]  WITH CHECK ADD  CONSTRAINT [FK_MetricDescriptions_Metrics] FOREIGN KEY([MetricID])
REFERENCES [dbo].[Metrics] ([ID])
GO

ALTER TABLE [dbo].[MetricDescriptions] CHECK CONSTRAINT [FK_MetricDescriptions_Metrics]
GO

ALTER TABLE [dbo].[MetricName]  WITH CHECK ADD  CONSTRAINT [FK_Metric_MetricName] FOREIGN KEY([NameID])
REFERENCES [dbo].[Metrics] ([ID])
GO

ALTER TABLE [dbo].[MetricName] CHECK CONSTRAINT [FK_Metric_MetricName]
GO

ALTER TABLE [dbo].[MetricGroupMap]  WITH CHECK ADD  CONSTRAINT [FK_MetricGroupMap_MetricGroups] FOREIGN KEY([GroupID])
REFERENCES [dbo].[MetricGroups] ([ID])
GO

ALTER TABLE [dbo].[MetricGroupMap] CHECK CONSTRAINT [FK_MetricGroupMap_MetricGroups]
GO

ALTER TABLE [dbo].[MetricGroupMap]  WITH CHECK ADD  CONSTRAINT [FK_MetricGroupMap_Metrics] FOREIGN KEY([MetricID])
REFERENCES [dbo].[Metrics] ([ID])
GO

ALTER TABLE [dbo].[MetricGroupMap] CHECK CONSTRAINT [FK_MetricGroupMap_Metrics]
GO

ALTER TABLE [dbo].[MetricGroups]  WITH CHECK ADD  CONSTRAINT [FK_MetricGroups_MetricGroups] FOREIGN KEY([ID])
REFERENCES [dbo].[MetricGroups] ([ID])
GO

ALTER TABLE [dbo].[MetricGroups] CHECK CONSTRAINT [FK_MetricGroups_MetricGroups]
GO

