USE [ReportBuilder]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/* DASHBOARD */

CREATE TABLE [dbo].[Dashboards](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](30) NOT NULL,
	[Definition] [nvarchar](2000) NULL,
	[CreationDate] [nvarchar](30) NULL,
	[ModificationDate] [nvarchar](30) NULL,
	[DeletionDate] [nvarchar](30) NULL,
	[IsDeleted] [bit] NULL,
 CONSTRAINT [PK_Dashboard] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Dashboards] ADD  DEFAULT ((0)) FOR [IsDeleted]
GO

/* DASHBOARD COMPONENT */

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DashboardComponents](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DashboardId] [int] NOT NULL,
	[Title] [varchar](50) NOT NULL,
	[Type] [int] NOT NULL,
	[Definition] [nvarchar](2000) NULL,
	[CreationDate] [nvarchar](30)  NULL,
	[ModificationDate] [nvarchar](30) NULL,
	[DeletionDate] [nvarchar](30) NULL,
	[IsDeleted] [bit] NULL,
 CONSTRAINT [PK_DashboardComponents] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DashboardComponents] ADD  DEFAULT ((0)) FOR [IsDeleted]
GO

/* RERPORT COMPONENT */

CREATE TABLE [dbo].[ReportComponents](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](30) NOT NULL,
	[Type] [int] NOT NULL,
	[Definition] [nvarchar](2000) NULL,
	[CreationDate] [nvarchar](30) NULL,
	[ModificationDate] [nvarchar](30) NULL,
	[DeletionDate] [nvarchar](30) NULL,
	[IsDeleted] [bit] NULL,
 CONSTRAINT [PK_ReportComponents] PRIMARY KEY CLUSTERED 
(
	[ReportId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ReportComponents] ADD  DEFAULT ((0)) FOR [IsDeleted]
GO



/* METRIC */
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Metrics](
	[ID] [int] NOT NULL,
	[Mnemonic] [varchar](50) NOT NULL,
	[DataType] [varchar](12) NOT NULL,
 CONSTRAINT [PK_Metrics] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/* METRIC GROUPS */
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MetricGroups](
	[ID] [int] NOT NULL,
	[GroupName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_MetricGroups] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/* METRIC GROUPS <MAP> METRIC */
CREATE TABLE [dbo].[MetricGroupMetric](
	[ID] [int] NOT NULL,
	[GroupID] [int] NOT NULL,
	[MetricID] [int] NOT NULL,
 CONSTRAINT [PK_MetricGroupMap] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UniqueCombos] UNIQUE NONCLUSTERED 
(
	[GroupID] ASC,
	[MetricID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[MetricID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/* METRIC NAME */
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MetricName](
	[ID] [int] NOT NULL,
	[MetricID] [int] NOT NULL,
	[Language] [varchar](50) NOT NULL,
	[DisplayName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_MetricName] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/* METRIC DISCRIPTION */
CREATE TABLE [dbo].[MetricDescriptions](
	[ID] [int] NOT NULL,
	[MetricID] [int] NOT NULL,
	[Description] [nvarchar](300) NULL,
 CONSTRAINT [PK_MetricDescriptions] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE METRIC] UNIQUE NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[MetricID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MetricDescriptions]  WITH CHECK ADD  CONSTRAINT [FK_MetricDescriptions_Metrics] FOREIGN KEY([MetricID])
REFERENCES [dbo].[Metrics] ([ID])
GO

ALTER TABLE [dbo].[MetricDescriptions] CHECK CONSTRAINT [FK_MetricDescriptions_Metrics]
GO

ALTER TABLE [dbo].[MetricName]  WITH CHECK ADD  CONSTRAINT [FK_Metric_MetricName] FOREIGN KEY([MetricID])
REFERENCES [dbo].[Metrics] ([ID])
GO

ALTER TABLE [dbo].[MetricName] CHECK CONSTRAINT [FK_Metric_MetricName]
GO

ALTER TABLE [dbo].[MetricGroupMetric]  WITH CHECK ADD  CONSTRAINT [FK_MetricGroupMap_MetricGroups] FOREIGN KEY([GroupID])
REFERENCES [dbo].[MetricGroups] ([ID])
GO

ALTER TABLE [dbo].[MetricGroupMetric] CHECK CONSTRAINT [FK_MetricGroupMap_MetricGroups]
GO

ALTER TABLE [dbo].[MetricGroupMetric]  WITH CHECK ADD  CONSTRAINT [FK_MetricGroupMap_Metrics] FOREIGN KEY([MetricID])
REFERENCES [dbo].[Metrics] ([ID])
GO

ALTER TABLE [dbo].[MetricGroupMetric] CHECK CONSTRAINT [FK_MetricGroupMap_Metrics]
GO

ALTER TABLE [dbo].[MetricGroups]  WITH CHECK ADD  CONSTRAINT [FK_MetricGroups_MetricGroups] FOREIGN KEY([ID])
REFERENCES [dbo].[MetricGroups] ([ID])
GO

ALTER TABLE [dbo].[MetricGroups] CHECK CONSTRAINT [FK_MetricGroups_MetricGroups]
GO

